### ISSUE TITLE
OTP?

### ISSUE THREAD

**Issue by zeke** [keathley/keathley.github.io#1]
Hi there! I came across this post via [Elixir Radar](http://plataformatec.com.br/elixir-radar): http://keathley.io/elixir/phoenix/2016/01/14/phoenix-directories.html

> But remember that Phoenix is just OTP!

I don't know what OTP means. A link or explanation would be helpful.

https://en.wikipedia.org/wiki/OTP

**Comment by keathley** [comment]
Thats a great point @zeke! Just for clarification, OTP stands for the [Open Telecom Platform](https://en.wikipedia.org/wiki/Open_Telecom_Platform) and its a set of behaviours and patterns used to build erlang and elixir applications. I've added a link to the [elixir guides on OTP](http://elixir-lang.org/getting-started/mix-otp/introduction-to-mix.html) in the post.

**Comment by zeke** [comment]
Nice. Thanks!
