### ISSUE TITLE
Re"guard"ing Elixir Guard Clauses Blog (ouch)

### ISSUE THREAD

**Issue by ghost** [keathley/keathley.github.io#2]
Howdy!

Your article on guard functions is great, and being so, it's number 2 on google when searching for "elixir guards". It has helped me, and I wanted to say thanks. But not just that...I also wanted to point out that I _think_ your naming conventions might should be edited since google has made it the de facto learning resource for the things.

http://elixir-lang.org/docs/master/elixir/naming-conventions.html#is_-prefix-is_foo

I think a good place for it would be to change it once it's turned into a guard-valid macro in the "Defining our own guards - Macros FTW." section. I could do a PR, but I thought that would be weird doing a PR on someone's blog page and it wouldn't be your own edit...But if you're down, I could do it!

Thanks again for the great article. 

PS My bad for the trite pun.

**Comment by keathley** [comment]
Thanks for the feedback! I'm glad that you found it useful. I think your point about naming is really good. Thats not something that I thought of before but I can see how it would be useful. I'll make some edits and push up a new version. 👍
